/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Scene3D/scene1.gltf 
Author: EdwinRC (https://sketchfab.com/Edwin3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-ufo-scene-207cb85b20a5430eb636966d408f1bd0
Title: Low Poly UFO Scene
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene1.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[538.08, 740.191, -893.765]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={24.516}>
        <mesh geometry={nodes.Plane000_M20_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Plane000_M3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Plane000_M14_0.geometry} material={materials.material_2} />
      </group>
      <group position={[-894.056, 118.789, -828.982]} rotation={[0, 1.071, 0]} scale={[177.54, 76.038, 76.038]}>
        <mesh geometry={nodes.Plane003_M19_0.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Plane003_Material_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane003_M1_0.geometry} material={materials.material_5} />
      </group>
      <group position={[1277.967, -0.065, 577.664]} rotation={[-Math.PI / 2, 0, -0.264]} scale={5.276}>
        <mesh geometry={nodes.Cylinder014_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Cylinder014_M9_0.geometry} material={materials.material_7} />
      </group>
      <group position={[-910.585, -1.006, -1045.425]} rotation={[-Math.PI / 2, 0, 0]} scale={6.558}>
        <mesh geometry={nodes.Cylinder004_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Cylinder004_M9_0.geometry} material={materials.material_7} />
      </group>
      <group position={[-943.983, -5.612, -992.822]} rotation={[-Math.PI / 2, 0, -0.264]} scale={5.276}>
        <mesh geometry={nodes.Cylinder013_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Cylinder013_M9_0.geometry} material={materials.material_7} />
      </group>
      <group position={[1369.739, -16.721, 566.795]} rotation={[-Math.PI / 2, 0, 2.054]} scale={47.685}>
        <mesh geometry={nodes.Circle011_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle011_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[-979.185, -0.337, -1092.093]} rotation={[-Math.PI / 2, 0, -2.753]} scale={47.685}>
        <mesh geometry={nodes.Circle009_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle009_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[1047.212, 1256.729, -1287.62]} rotation={[-1.571, 0, -2.179]} scale={[17.019, 682.212, 2.388]}>
        <mesh geometry={nodes.Cube021_M19_0.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Cube021_M1_0.geometry} material={materials.material_5} />
      </group>
      <group position={[1040.887, 1181.088, -1282.675]} rotation={[-Math.PI / 2, 0, -0.612]} scale={32.816}>
        <mesh geometry={nodes.Plane002_M7_0.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Plane002_M12_0.geometry} material={materials.material_10} />
        <mesh geometry={nodes.Plane002_M8_0.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Plane002_M2_0.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Plane002_M14_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane002_M1_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Plane002_M3_0.geometry} material={materials.material_1} />
      </group>
      <group position={[-23.093, 141.258, -1344.106]} rotation={[-Math.PI / 2, 0, -1.008]} scale={47.685}>
        <mesh geometry={nodes.Circle008_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle008_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[-342.48, 122.717, -1283.193]} rotation={[-Math.PI / 2, 0, -0.015]} scale={47.685}>
        <mesh geometry={nodes.Circle007_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle007_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[-204.152, 72.836, -1056.209]} rotation={[-Math.PI / 2, 0, 0]} scale={47.685}>
        <mesh geometry={nodes.Circle006_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle006_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[-751.768, 48.071, 792.776]} rotation={[-Math.PI / 2, 0, -1.9]} scale={47.685}>
        <mesh geometry={nodes.Circle005_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle005_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[-953.456, 27.733, 840.637]} rotation={[-Math.PI / 2, 0, 2.638]} scale={47.685}>
        <mesh geometry={nodes.Circle004_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle004_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[982.944, 24.693, -983.99]} rotation={[-Math.PI / 2, 0, 0]} scale={47.685}>
        <mesh geometry={nodes.Circle003_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle003_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[-836.66, 13.794, 548.982]} rotation={[-Math.PI / 2, 0, 0]} scale={47.685}>
        <mesh geometry={nodes.Circle002_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle002_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[844.616, 26.306, -1210.974]} rotation={[-Math.PI / 2, 0, 1.193]} scale={47.685}>
        <mesh geometry={nodes.Circle001_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle001_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[1083.464, 26.306, -1206.585]} rotation={[-Math.PI / 2, 0, 0]} scale={47.685}>
        <mesh geometry={nodes.Circle_M18001_0.geometry} material={materials['M18.001']} />
        <mesh geometry={nodes.Circle_M17_0.geometry} material={materials.material_8} />
      </group>
      <group position={[729.62, 10.499, 180.882]} rotation={[-Math.PI / 2, 0, 0]} scale={[29.748, 29.748, 3.389]}>
        <mesh geometry={nodes.Cube010_M14_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube010_M4_0.geometry} material={materials.material_15} />
        <mesh geometry={nodes.Cube010_M3_0.geometry} material={materials.material_1} />
      </group>
      <group position={[665.25, 10.499, -379.571]} rotation={[-Math.PI / 2, 0, 0]} scale={[29.748, 29.748, 3.389]}>
        <mesh geometry={nodes.Cube009_M14_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube009_M4_0.geometry} material={materials.material_15} />
        <mesh geometry={nodes.Cube009_M3_0.geometry} material={materials.material_1} />
      </group>
      <group position={[-0.895, 10.499, -494.898]} rotation={[-Math.PI / 2, 0, 0]} scale={[29.748, 29.748, 3.389]}>
        <mesh geometry={nodes.Cube008_M14_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube008_M4_0.geometry} material={materials.material_15} />
        <mesh geometry={nodes.Cube008_M3_0.geometry} material={materials.material_1} />
      </group>
      <group position={[55.946, 10.499, 206.144]} rotation={[-Math.PI / 2, 0, 0]} scale={[29.748, 29.748, 3.389]}>
        <mesh geometry={nodes.Cube007_M14_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Cube007_M4_0.geometry} material={materials.material_15} />
        <mesh geometry={nodes.Cube007_M3_0.geometry} material={materials.material_1} />
      </group>
      <group position={[656.045, 89.351, 30.455]} rotation={[-Math.PI / 2, 0, 1.403]} scale={[4.676, 4.676, 51.807]}>
        <mesh geometry={nodes.Cylinder030_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cylinder030_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder030_M13_0.geometry} material={materials.material_18} />
      </group>
      <group position={[410.843, 89.351, 248.841]} rotation={[-Math.PI / 2, 0, 0.056]} scale={[4.676, 4.676, 51.807]}>
        <mesh geometry={nodes.Cylinder029_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cylinder029_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder029_M13_0.geometry} material={materials.material_18} />
      </group>
      <group position={[89.067, 89.351, 102.424]} rotation={[-Math.PI / 2, 0, -1.006]} scale={[4.676, 4.676, 51.807]}>
        <mesh geometry={nodes.Cylinder028_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cylinder028_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder028_M13_0.geometry} material={materials.material_18} />
      </group>
      <group position={[579.416, 89.021, -271.577]} rotation={[-Math.PI / 2, 0, 2.184]} scale={[4.676, 4.676, 51.807]}>
        <mesh geometry={nodes.Cylinder027_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cylinder027_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder027_M13_0.geometry} material={materials.material_18} />
      </group>
      <group position={[307.596, 89.351, -422.802]} rotation={[-Math.PI / 2, 0, 3.078]} scale={[4.676, 4.676, 51.807]}>
        <mesh geometry={nodes.Cylinder026_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cylinder026_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder026_M13_0.geometry} material={materials.material_18} />
      </group>
      <group position={[-220.356, 203.103, -170.742]} rotation={[-Math.PI / 2, 0, 0.05]} scale={[100, 100, 138.274]}>
        <mesh geometry={nodes.Cube006_M9L_0.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Cube006_M3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube006_M1_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Cube006_M12L_0.geometry} material={materials.M12L} />
        <mesh geometry={nodes.Cube006_M8_0.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Cube006_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cube006_M9_0.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Cube006_M19_0.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Cube006_M11L_0.geometry} material={materials.M11L} />
        <mesh geometry={nodes.Cube006_M2_0.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Cube006_M12_0.geometry} material={materials.material_10} />
        <mesh geometry={nodes.Cube006_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-325.489, 54.208, 46.031]} rotation={[0, -1.521, Math.PI]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder023_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder023_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-343.299, 54.208, -309.72]} rotation={[0, -1.521, Math.PI]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder022_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder022_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-91.233, 54.208, 34.303]} rotation={[Math.PI, 1.521, 0]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder021_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder021_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-109.043, 54.208, -321.448]} rotation={[Math.PI, 1.521, 0]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder019_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder019_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[71.634, 89.351, -286.254]} rotation={[-Math.PI / 2, 0, -1.974]} scale={[4.676, 4.676, 51.807]}>
        <mesh geometry={nodes.Cylinder020_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cylinder020_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder020_M13_0.geometry} material={materials.material_18} />
      </group>
      <group position={[1237.033, 50.242, -311.877]} rotation={[0, 1.137, -Math.PI]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder018_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder018_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[1087.344, 50.242, 11.34]} rotation={[0, 1.137, -Math.PI]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder017_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder017_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[1024.2, 50.242, -410.444]} rotation={[Math.PI, -1.137, 0]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder016_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder016_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[874.512, 50.242, -87.228]} rotation={[Math.PI, -1.137, 0]} scale={[43.139, 43.139, 52.635]}>
        <mesh geometry={nodes.Cylinder015_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder015_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[1068.4, 199.137, -230.232]} rotation={[-Math.PI / 2, 0, -0.434]} scale={[100, 100, 138.274]}>
        <mesh geometry={nodes.Cube004_M9L_0.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Cube004_M3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube004_M1_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Cube004_M12L_0.geometry} material={materials.M12L} />
        <mesh geometry={nodes.Cube004_M8_0.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Cube004_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cube004_M9_0.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Cube004_M19_0.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Cube004_M11L_0.geometry} material={materials.M11L} />
        <mesh geometry={nodes.Cube004_M2_0.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Cube004_M12_0.geometry} material={materials.material_10} />
        <mesh geometry={nodes.Cube004_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[525.831, 281.11, 11.844]} rotation={[-Math.PI / 2, 0.594, 0]} scale={[3.625, 3.49, 81.755]}>
        <mesh geometry={nodes.Cylinder005_M1_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Cylinder005_M8_0.geometry} material={materials.material_11} />
      </group>
      <group position={[363.336, 167.376, -0.575]} rotation={[-Math.PI / 2, 0, 0]} scale={152.757}>
        <mesh geometry={nodes.Cylinder007_M1_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Cylinder007_M3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cylinder007_M9L_0.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Cylinder007_M7_0.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Cylinder007_M2_0.geometry} material={materials.material_12} />
      </group>
      <group position={[-719.525, 242.846, -72.529]} rotation={[-Math.PI / 2, 0, -1.859]} scale={[48.472, 63.834, 9.574]}>
        <mesh geometry={nodes.Cube_M1_0.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Cube_M3_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Cube_M7_0.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Cube_M9L_0.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Cube_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cube_M2_0.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Cube_M8_0.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Cube_M6_0.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Cube_M19_0.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Cube_M4_0.geometry} material={materials.material_15} />
      </group>
      <group position={[324.468, 8.147, -154.891]} rotation={[Math.PI / 2, 0, 0]} scale={[-1388.624, 475.744, 76.365]}>
        <mesh geometry={nodes.Plane004_M14_0.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Plane004_M13_0.geometry} material={materials.material_18} />
        <mesh geometry={nodes.Plane004_M3_0.geometry} material={materials.material_1} />
      </group>
      <group position={[-500.437, 51.025, -133.707]} rotation={[Math.PI, 0.288, 0]} scale={[43.565, 43.565, 53.155]}>
        <mesh geometry={nodes.Cylinder002_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder002_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-567.591, 51.025, 92.683]} rotation={[0, -0.288, -Math.PI]} scale={[43.565, 43.565, 53.155]}>
        <mesh geometry={nodes.Cylinder001_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder001_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-911.295, 51.025, -9.271]} rotation={[0, -0.288, -Math.PI]} scale={[43.565, 43.565, 53.155]}>
        <mesh geometry={nodes.Cylinder000_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder000_M6_0.geometry} material={materials.material_16} />
      </group>
      <group position={[-844.141, 51.025, -235.66]} rotation={[Math.PI, 0.288, 0]} scale={[43.565, 43.565, 53.155]}>
        <mesh geometry={nodes.Cylinder003_M5_0.geometry} material={materials.material_17} />
        <mesh geometry={nodes.Cylinder003_M6_0.geometry} material={materials.material_16} />
      </group>
      <mesh geometry={nodes.Icosphere002_M3_0.geometry} material={materials.material_1} position={[-650.176, 34.699, 553.078]} rotation={[0.51, 0.367, -1.769]} scale={100} />
      <mesh geometry={nodes.Cube016_M18_0.geometry} material={materials.material_13} position={[-966.074, 21.077, 588.365]} rotation={[-Math.PI / 2, 0, -0.006]} scale={9.265} />
      <mesh geometry={nodes.Cube015_M18_0.geometry} material={materials.material_13} position={[-807.66, 44.786, 802.577]} rotation={[-Math.PI / 2, 0, -1.7]} scale={9.265} />
      <mesh geometry={nodes.Cube014_M18_0.geometry} material={materials.material_13} position={[-1078.385, 18.552, 784.004]} rotation={[-Math.PI / 2, 0, -0.006]} scale={9.265} />
      <mesh geometry={nodes.Cube013_M18_0.geometry} material={materials.material_13} position={[-870.559, 46.256, 725.701]} rotation={[-Math.PI / 2, 0, -1.597]} scale={9.265} />
      <mesh geometry={nodes.Cube012_M18_0.geometry} material={materials.material_13} position={[-74.977, 82.94, -1096.137]} rotation={[-Math.PI / 2, 0, -2.1]} scale={9.265} />
      <mesh geometry={nodes.Cube011_M18_0.geometry} material={materials.material_13} position={[-205.525, 108.811, -1176.927]} rotation={[-Math.PI / 2, 0, -0.695]} scale={9.265} />
      <mesh geometry={nodes.Cube001_M18_0.geometry} material={materials.material_13} position={[741.329, 17.38, -900.61]} rotation={[-Math.PI / 2, 0, -0.695]} scale={9.265} />
      <mesh geometry={nodes.Cube002_M18_0.geometry} material={materials.material_13} position={[1089.409, 40.299, -1115.969]} rotation={[-Math.PI / 2, 0, 1.115]} scale={9.265} />
      <mesh geometry={nodes.Icosphere001_M3_0.geometry} material={materials.material_1} position={[688.33, 8.762, -941.977]} rotation={[-1.989, 0, 0]} scale={48.45} />
      <mesh geometry={nodes.Icosphere_M3_0.geometry} material={materials.material_1} position={[709.416, -31.357, -1045.559]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Plane001_M16_0.geometry} material={materials.material_14} position={[324.468, -825.161, -154.891]} rotation={[Math.PI / 2, 0, 0]} scale={[-1388.624, 475.744, 76.365]} />
      <mesh geometry={nodes.Cylinder025_M5_0.geometry} material={materials.material_17} position={[-208.144, 37.67, 42.545]} rotation={[-Math.PI, 1.521, 1.571]} scale={15.22} />
      <mesh geometry={nodes.Cylinder024_M5_0.geometry} material={materials.material_17} position={[-225.969, 37.67, -313.492]} rotation={[-Math.PI, 1.521, 1.571]} scale={15.22} />
    </group>
  )
}

useGLTF.preload('/scene1.gltf')
